apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

# kubectl create -f nginx-pod.yml --save-config
# kubectl describe pod my-nginx
# kubectl apply -f nginx-pod.yml
# kubectl exec my-nginx -it sh
# kubectl edit -f nginx-pod.yml
